### ISSUE TITLE
Provide ARM template for Setup

### ISSUE THREAD

**Issue by ezwiefel** [microsoft/MCW-Big-data-analytics-and-visualization#1]
We should have a "Deploy to Azure" button to automate as much of setup as possible.

**Comment by joelhulen** [comment]
Not a bad idea. I wonder if it's worth having some things be set up manually so they know the process?

**Comment by ezwiefel** [comment]
I think it makes sense to have the instructions there - but also script out as much as possible. 

That way, you can show the attendees what setup looks like, but leave more time for the data science / data engineering tasks.

**Comment by nabeelderhem** [comment]
I agree with Eric

**Comment by joelhulen** [comment]
I agree that having an ARM template would be helpful. I'm not sure I have time to put one together and test it at this point. Perhaps this is something we can add in a future update?

**Comment by DawnmarieDesJardins** [comment]
Tagging this one as an enhancement for future consideration
