### ISSUE TITLE
Secret scanning alert

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Big-data-analytics-and-visualization#103]
Received this notice. Please review and advise.
Close as options are Revoked, False positive, Used in tests, and Won't fix

![image](https://user-images.githubusercontent.com/39317565/170122218-98d828eb-f39f-48e3-a6ce-1bad353f9dde.png)

![image](https://user-images.githubusercontent.com/39317565/170122290-71a2b711-2d4c-46b7-a677-e308960472c0.png)

Thanks!

**Comment by feaselkl** [comment]
Probably either used in tests or false positive. It is an example token, not one in actual use.

**Comment by DawnmarieDesJardins** [comment]
Done, thanks for checking.  Closing issue as complete.
