### ISSUE TITLE
Deploy as Web Service Notebook cell

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Big-data-analytics-and-visualization#96]
Received via email.  Customer reached out to one of our CSAs asking for help.  CSA is unable to replicate their error as she has System Admin rights.  She did confirm with her customer they followed step 2 in the requirements section of the Before HOL document.  

Dear Team,
One of my customers was trying to implement this MCW-Big-data-and-visualization/Before the HOL - Big data and visualization.md at main · microsoft/MCW-Big-data-and-visualization · GitHub but while running the 03 Deploy as Web Service Notebook cell :
service_name = "sparkmlservicedb001"

from azureml.core.webservice import AciWebservice, Webservice
from azureml.exceptions import WebserviceException

try:
    # if you want to get existing service below is the command
    # since aci name needs to be unique in subscription deleting existing aci if any
    # we use aci_service_name to create azure aci
    service = Webservice(ws, name=service_name)
    if service:
        service.delete()
except WebserviceException as e:
    print()

service = Model.deploy(ws, service_name, [mymodel], inference_config, aci_config)

service.wait_for_deployment(True)
print(service.state)

It runs into the following error : 
Tips: You can try get_logs(): https://aka.ms/debugimage#dockerlog or local deployment: https://aka.ms/debugimage#debug-locally to debug if deployment takes longer than 10 minutes. FailedService deployment polling reached non-successful terminal state, current service state: Transitioning Operation ID: f1ce49b7-4deb-42d2-9f11-41f27f7ca70e More information can be found here: https://amlbigdastorageeba026c63.blob.core.windows.net/azureml/ImageLogs/f1ce49b7-4deb-42d2-9f11-41f27f7ca70e/build.log?sv=2019-02-02&sr=b&sig=Rrn%2FUFkHjlxB1aje9kxETlWdCUEj9O8x7OfxbMHJBNk%3D&st=2021-08-04T01%3A32%3A42Z&se=2021-08-04T09%3A37%3A42Z&sp=r 
Error: { "code": "AciDeploymentFailed", "statusCode": 401, "message": "Failed to fetch details for Environment with Name: AzureML-PySpark-MmlSpark-0.15 Version: 45 Reason: Authentication failed for Container Registry: hub.docker.com..", "details": [] }

After researching , I found there is a common issue identified since 2019 as follows: the permission list is not recognizable by ACR if the current login user has a classic subscription administrator role, such as Service Administrator and Co-Administrator”

Any suggested workarounds ?

**Comment by menatallahMohamed** [comment]
Thank you @Dawnmarie
I am available for any questions or suggested workarounds to directly share them with my customer as the customer has a management meeting to showcase this MCW as it is a comprehensive use case to what they are trying to achieve

Appreciated

**Comment by timahenning** [comment]
Hi @menatallahMohamed,

We are working on your issue.  Unfortunately, at the moment we cannot reproduce the error.

Tim

**Comment by menatallahMohamed** [comment]
I am able to reproduce this error actually as detailed in my above email

**Comment by DawnmarieDesJardins** [comment]
Marking this issue as an enhancement.  We have scheduled the workshop to receive an update and we will resolve the issue in the needed update.  In the meantime, you can skip this exercise to complete the rest of the lab.
